server:
  servlet:
    context-path: /api
  compression:
    enabled: true
  port: 8090
spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/talk
    username: postgres
    password: bessem
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        jdbc:
          lob:
            non_contextual_creation: true
  quartz:
    job-store-type: jdbc
    jdbc:
      initialize-schema: never
  jackson:
    serialization:
      FAIL_ON_EMPTY_BEANS: false